// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: ws.base.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CMsgProtoBufHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserHash        []byte `protobuf:"bytes,1,opt,name=UserHash,proto3" json:"UserHash,omitempty"`
	IpAddr          []byte `protobuf:"bytes,2,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	SessionClientId int32  `protobuf:"varint,3,opt,name=SessionClientId,proto3" json:"SessionClientId,omitempty"`
	AuthToken       []byte `protobuf:"bytes,4,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
}

func (x *CMsgProtoBufHeader) Reset() {
	*x = CMsgProtoBufHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMsgProtoBufHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgProtoBufHeader) ProtoMessage() {}

func (x *CMsgProtoBufHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ws_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgProtoBufHeader.ProtoReflect.Descriptor instead.
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) {
	return file_ws_base_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgProtoBufHeader) GetUserHash() []byte {
	if x != nil {
		return x.UserHash
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetIpAddr() []byte {
	if x != nil {
		return x.IpAddr
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetSessionClientId() int32 {
	if x != nil {
		return x.SessionClientId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetAuthToken() []byte {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type MsgEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      EMSG                   `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EMSG" json:"type,omitempty"`
	Data      []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MsgEvent) Reset() {
	*x = MsgEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEvent) ProtoMessage() {}

func (x *MsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEvent.ProtoReflect.Descriptor instead.
func (*MsgEvent) Descriptor() ([]byte, []int) {
	return file_ws_base_proto_rawDescGZIP(), []int{1}
}

func (x *MsgEvent) GetType() EMSG {
	if x != nil {
		return x.Type
	}
	return EMSG_INVALID
}

func (x *MsgEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_ws_base_proto protoreflect.FileDescriptor

var file_ws_base_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x77, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x12, 0x43, 0x4d, 0x73, 0x67,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x49, 0x70, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7a, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d, 0x53,
	0x47, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_base_proto_rawDescOnce sync.Once
	file_ws_base_proto_rawDescData = file_ws_base_proto_rawDesc
)

func file_ws_base_proto_rawDescGZIP() []byte {
	file_ws_base_proto_rawDescOnce.Do(func() {
		file_ws_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_base_proto_rawDescData)
	})
	return file_ws_base_proto_rawDescData
}

var file_ws_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ws_base_proto_goTypes = []interface{}{
	(*CMsgProtoBufHeader)(nil),    // 0: proto.CMsgProtoBufHeader
	(*MsgEvent)(nil),              // 1: proto.MsgEvent
	(EMSG)(0),                     // 2: proto.EMSG
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ws_base_proto_depIdxs = []int32{
	2, // 0: proto.MsgEvent.type:type_name -> proto.EMSG
	3, // 1: proto.MsgEvent.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ws_base_proto_init() }
func file_ws_base_proto_init() {
	if File_ws_base_proto != nil {
		return
	}
	file_ws_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ws_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMsgProtoBufHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_base_proto_goTypes,
		DependencyIndexes: file_ws_base_proto_depIdxs,
		MessageInfos:      file_ws_base_proto_msgTypes,
	}.Build()
	File_ws_base_proto = out.File
	file_ws_base_proto_rawDesc = nil
	file_ws_base_proto_goTypes = nil
	file_ws_base_proto_depIdxs = nil
}
