// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: ws.chat.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChatMsgEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sender      *User                  `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Reciever    *User                  `protobuf:"bytes,3,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Attachments []string               `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Emojies     []uint64               `protobuf:"varint,5,rep,packed,name=emojies,proto3" json:"emojies,omitempty"`
	Mentions    []uint64               `protobuf:"varint,6,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ChatMsgEvent) Reset() {
	*x = ChatMsgEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgEvent) ProtoMessage() {}

func (x *ChatMsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgEvent.ProtoReflect.Descriptor instead.
func (*ChatMsgEvent) Descriptor() ([]byte, []int) {
	return file_ws_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsgEvent) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatMsgEvent) GetSender() *User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ChatMsgEvent) GetReciever() *User {
	if x != nil {
		return x.Reciever
	}
	return nil
}

func (x *ChatMsgEvent) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChatMsgEvent) GetEmojies() []uint64 {
	if x != nil {
		return x.Emojies
	}
	return nil
}

func (x *ChatMsgEvent) GetMentions() []uint64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMsgEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ChatMsgDeletedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *ChatMsgDeletedEvent) Reset() {
	*x = ChatMsgDeletedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsgDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgDeletedEvent) ProtoMessage() {}

func (x *ChatMsgDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgDeletedEvent.ProtoReflect.Descriptor instead.
func (*ChatMsgDeletedEvent) Descriptor() ([]byte, []int) {
	return file_ws_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMsgDeletedEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMsgDeletedEvent) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_ws_chat_proto protoreflect.FileDescriptor

var file_ws_chat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x73, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x02, 0x0a, 0x0c, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x73, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69,
	0x65, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x6f, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_chat_proto_rawDescOnce sync.Once
	file_ws_chat_proto_rawDescData = file_ws_chat_proto_rawDesc
)

func file_ws_chat_proto_rawDescGZIP() []byte {
	file_ws_chat_proto_rawDescOnce.Do(func() {
		file_ws_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_chat_proto_rawDescData)
	})
	return file_ws_chat_proto_rawDescData
}

var file_ws_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ws_chat_proto_goTypes = []interface{}{
	(*ChatMsgEvent)(nil),          // 0: proto.ChatMsgEvent
	(*ChatMsgDeletedEvent)(nil),   // 1: proto.ChatMsgDeletedEvent
	(*User)(nil),                  // 2: proto.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ws_chat_proto_depIdxs = []int32{
	2, // 0: proto.ChatMsgEvent.sender:type_name -> proto.User
	2, // 1: proto.ChatMsgEvent.reciever:type_name -> proto.User
	3, // 2: proto.ChatMsgEvent.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: proto.ChatMsgDeletedEvent.deleted_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ws_chat_proto_init() }
func file_ws_chat_proto_init() {
	if File_ws_chat_proto != nil {
		return
	}
	file_grpc_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ws_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsgEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsgDeletedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_chat_proto_goTypes,
		DependencyIndexes: file_ws_chat_proto_depIdxs,
		MessageInfos:      file_ws_chat_proto_msgTypes,
	}.Build()
	File_ws_chat_proto = out.File
	file_ws_chat_proto_rawDesc = nil
	file_ws_chat_proto_goTypes = nil
	file_ws_chat_proto_depIdxs = nil
}
