// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: ws.media.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VoiceConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Muted    bool     `protobuf:"varint,2,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened bool     `protobuf:"varint,3,opt,name=deafened,proto3" json:"deafened,omitempty"`
	Talking  bool     `protobuf:"varint,4,opt,name=talking,proto3" json:"talking,omitempty"`
	User     *User    `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Theater  *Theater `protobuf:"bytes,6,opt,name=theater,proto3" json:"theater,omitempty"`
}

func (x *VoiceConnection) Reset() {
	*x = VoiceConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceConnection) ProtoMessage() {}

func (x *VoiceConnection) ProtoReflect() protoreflect.Message {
	mi := &file_ws_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceConnection.ProtoReflect.Descriptor instead.
func (*VoiceConnection) Descriptor() ([]byte, []int) {
	return file_ws_media_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceConnection) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *VoiceConnection) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

func (x *VoiceConnection) GetTalking() bool {
	if x != nil {
		return x.Talking
	}
	return false
}

func (x *VoiceConnection) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *VoiceConnection) GetTheater() *Theater {
	if x != nil {
		return x.Theater
	}
	return nil
}

var File_ws_media_proto protoreflect.FileDescriptor

var file_ws_media_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74,
	0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a,
	0x0f, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x66, 0x65, 0x6e,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65, 0x61, 0x66, 0x65, 0x6e,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x6c, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x61, 0x6c, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x07, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x52, 0x07,
	0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_media_proto_rawDescOnce sync.Once
	file_ws_media_proto_rawDescData = file_ws_media_proto_rawDesc
)

func file_ws_media_proto_rawDescGZIP() []byte {
	file_ws_media_proto_rawDescOnce.Do(func() {
		file_ws_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_media_proto_rawDescData)
	})
	return file_ws_media_proto_rawDescData
}

var file_ws_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ws_media_proto_goTypes = []interface{}{
	(*VoiceConnection)(nil), // 0: proto.VoiceConnection
	(*User)(nil),            // 1: proto.User
	(*Theater)(nil),         // 2: proto.Theater
}
var file_ws_media_proto_depIdxs = []int32{
	1, // 0: proto.VoiceConnection.user:type_name -> proto.User
	2, // 1: proto.VoiceConnection.theater:type_name -> proto.Theater
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ws_media_proto_init() }
func file_ws_media_proto_init() {
	if File_ws_media_proto != nil {
		return
	}
	file_grpc_user_proto_init()
	file_grpc_theater_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ws_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_media_proto_goTypes,
		DependencyIndexes: file_ws_media_proto_depIdxs,
		MessageInfos:      file_ws_media_proto_msgTypes,
	}.Build()
	File_ws_media_proto = out.File
	file_ws_media_proto_rawDesc = nil
	file_ws_media_proto_goTypes = nil
	file_ws_media_proto_depIdxs = nil
}
