// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: ws.state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingMsgEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State PERSONAL_STATE `protobuf:"varint,1,opt,name=state,proto3,enum=proto.PERSONAL_STATE" json:"state,omitempty"`
}

func (x *PingMsgEvent) Reset() {
	*x = PingMsgEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMsgEvent) ProtoMessage() {}

func (x *PingMsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMsgEvent.ProtoReflect.Descriptor instead.
func (*PingMsgEvent) Descriptor() ([]byte, []int) {
	return file_ws_state_proto_rawDescGZIP(), []int{0}
}

func (x *PingMsgEvent) GetState() PERSONAL_STATE {
	if x != nil {
		return x.State
	}
	return PERSONAL_STATE_OFFLINE
}

type PersonalStateMsgEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	State    PERSONAL_STATE `protobuf:"varint,2,opt,name=state,proto3,enum=proto.PERSONAL_STATE" json:"state,omitempty"`
	Activity *Activity      `protobuf:"bytes,3,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *PersonalStateMsgEvent) Reset() {
	*x = PersonalStateMsgEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalStateMsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalStateMsgEvent) ProtoMessage() {}

func (x *PersonalStateMsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalStateMsgEvent.ProtoReflect.Descriptor instead.
func (*PersonalStateMsgEvent) Descriptor() ([]byte, []int) {
	return file_ws_state_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalStateMsgEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PersonalStateMsgEvent) GetState() PERSONAL_STATE {
	if x != nil {
		return x.State
	}
	return PERSONAL_STATE_OFFLINE
}

func (x *PersonalStateMsgEvent) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type PersonalActivityMsgEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Activity *Activity `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *PersonalActivityMsgEvent) Reset() {
	*x = PersonalActivityMsgEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalActivityMsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalActivityMsgEvent) ProtoMessage() {}

func (x *PersonalActivityMsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalActivityMsgEvent.ProtoReflect.Descriptor instead.
func (*PersonalActivityMsgEvent) Descriptor() ([]byte, []int) {
	return file_ws_state_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalActivityMsgEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PersonalActivityMsgEvent) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

var File_ws_state_proto protoreflect.FileDescriptor

var file_ws_state_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x77, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67,
	0x4d, 0x73, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x41, 0x4c,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a,
	0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0x68, 0x0a, 0x18, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4d, 0x73,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_state_proto_rawDescOnce sync.Once
	file_ws_state_proto_rawDescData = file_ws_state_proto_rawDesc
)

func file_ws_state_proto_rawDescGZIP() []byte {
	file_ws_state_proto_rawDescOnce.Do(func() {
		file_ws_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_state_proto_rawDescData)
	})
	return file_ws_state_proto_rawDescData
}

var file_ws_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ws_state_proto_goTypes = []interface{}{
	(*PingMsgEvent)(nil),             // 0: proto.PingMsgEvent
	(*PersonalStateMsgEvent)(nil),    // 1: proto.PersonalStateMsgEvent
	(*PersonalActivityMsgEvent)(nil), // 2: proto.PersonalActivityMsgEvent
	(PERSONAL_STATE)(0),              // 3: proto.PERSONAL_STATE
	(*User)(nil),                     // 4: proto.User
	(*Activity)(nil),                 // 5: proto.Activity
}
var file_ws_state_proto_depIdxs = []int32{
	3, // 0: proto.PingMsgEvent.state:type_name -> proto.PERSONAL_STATE
	4, // 1: proto.PersonalStateMsgEvent.user:type_name -> proto.User
	3, // 2: proto.PersonalStateMsgEvent.state:type_name -> proto.PERSONAL_STATE
	5, // 3: proto.PersonalStateMsgEvent.activity:type_name -> proto.Activity
	4, // 4: proto.PersonalActivityMsgEvent.user:type_name -> proto.User
	5, // 5: proto.PersonalActivityMsgEvent.activity:type_name -> proto.Activity
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ws_state_proto_init() }
func file_ws_state_proto_init() {
	if File_ws_state_proto != nil {
		return
	}
	file_ws_enums_proto_init()
	file_grpc_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ws_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMsgEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalStateMsgEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ws_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalActivityMsgEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_state_proto_goTypes,
		DependencyIndexes: file_ws_state_proto_depIdxs,
		MessageInfos:      file_ws_state_proto_msgTypes,
	}.Build()
	File_ws_state_proto = out.File
	file_ws_state_proto_rawDesc = nil
	file_ws_state_proto_goTypes = nil
	file_ws_state_proto_depIdxs = nil
}
