name: Run tests on all branches

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.15.6'

    - name: Compile protobuffers
      run: make compile

    - name: Test
      run: make test
