name: Run tests on all branches

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install protoc `protobuf compiler`
      run: make install_protoc_linux_x86_64

    - name: Compile protobuffers
      run: make compile

    - name: Test
      run: make test
